apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: bfsltomcat 
spec:
  replicas: 2 
  selector:
   matchLabels:
    app: bfsltomcat 
  template:
    metadata: 
      labels:
        app: bfsltomcat
    spec:
      containers:
      - name: bfsltomcat
        image: jijjoe001/sprint6dockerjenkinsgcloud:tagversion 
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: bfsltomcat-svc 
  labels:
    app: bfsltomcat 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080 
  selector:
    app: bfsltomcat
